### ISSUE TITLE
rails 5 cannot run rails g ads:install

### ISSUE THREAD

**Issue by vtoanb** [mmontossi/ads-rails#4]
rails 5 cannot find generator ads:install, I use postgresql.

**Comment by mmontossi** [comment]
Hi @vtoanb, currently none of the gems are compatible with rails 5, I will be fixing this as soon as possible.

Thanks for open the issue, I won't close it yet, so I can let you know when the new version with the upgrade is released.

**Comment by mmontossi** [comment]
Done! Now you can use version 5.1.0 for Rails 5.1.
