### ISSUE TITLE
Height and width is not present.

### ISSUE THREAD

**Issue by sharwanjha8** [mmontossi/ads-rails#5]
Hi I am using your gem for google adds but the height and width of the div is not setup. 

I also tried with customised add.rb with static values also. Class is also not applied for the same.

**Comment by mmontossi** [comment]
The syntax is like this:

`<%= google_adsense_include_tag width: 300, height: 250, ... %>`

Let me know if that was the issue.

I will close the issue, feel free to reply if that didn't solve the problem.
